stun_servers:
  - stun3.l.google.com:19302
  - stun.l.google.com:19302

dns_servers:
  - name: "Quad9"
    address: "9.9.9.9:53"
    proto: "UDP"
  - name: "Cloudflare DoT"
    address: "1.1.1.1:853"
    proto: "DoT"


